### Registrar usuario
POST http://127.0.0.1:8000/api/register
Content-Type: application/json
Accept: application/json

{
  "name": "Sebastian",
  "email": "sebas@example.com",
  "password": "123456",
  "password_confirmation": "123456"
}



### Registro nuevo usuario
POST http://127.0.0.1:8000/api/register
Content-Type: application/json
Accept: application/json

{
  "name": "Mariano2",
  "email": "mariano2@example.com",
  "password": "12345678",
  "password_confirmation": "12345678"
}

### Login nuevo usuario
POST http://127.0.0.1:8000/api/login
Content-Type: application/json
Accept: application/json

{
  "email": "mariano2@example.com",
  "password": "12345678"
}

### Probar cursos
GET http://127.0.0.1:8000/api/cursos
Authorization: Bearer 1|07Eg5fSzBhvJNwKdcL7DFZ4q2s5CfdJBf3mHzPtv65fa2635
Accept: application/json


### Probar profesores
GET http://127.0.0.1:8000/api/profesores
Authorization: Bearer 1|07Eg5fSzBhvJNwKdcL7DFZ4q2s5CfdJBf3mHzPtv65fa2635
Accept: application/json



### Login con usuario
POST http://127.0.0.1:8000/api/login
Content-Type: application/json
Accept: application/json

{
  "email": "sebas@example.com",
  "password": "123456"
}


### Cerrar sesión (Logout)
POST http://127.0.0.1:8000/api/logout
Authorization: Bearer 1|mE7kHllIFHDt057ZvQSymBzdMqVCMIpiqmaaBBKg318abdd4


### Obtener todos los profesores
GET http://127.0.0.1:8000/api/profesores
Authorization: Bearer 1|mE7kHllIFHDt057ZvQSymBzdMqVCMIpiqmaaBBKg318abdd4
Accept: application/json

###Testprueba
GET http://127.0.0.1:8000/api/test-profesores
Authorization: Bearer 1|mE7kHllIFHDt057ZvQSymBzdMqVCMIpiqmaaBBKg318abdd4
Accept: application/json
